version: '3.4'

services:
  jse2eexpressserver:
    image: jse2eexpressserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
